### ISSUE TITLE
No need define output subscription-result

### ISSUE THREAD

**Issue by peipeiguo** [netconf-wg/rfc5277bis#2]
About [draft-ietf-netconf-subscribed-notifications-02](https://tools.ietf.org/html/draft-ietf-netconf-subscribed-notifications-02) bellow rpc, 
```
     +---x delete-subscription
     |  +---w input
     |  |  +---w identifier    subscription-id
     |  +--ro output
     |     +--ro subscription-result        subscription-result
     +---x kill-subscription
        +---w input
        |  +---w identifier                 subscription-id
        +--ro output
           +--ro subscription-result        subscription-result
```
Suggest remove output, because if success, we can use `<ok>` message, if failed, we can use `<rpc-error>` message. Should follow RFC6241 section 4, So I think no need define output.

**Comment by ericvoit** [comment]
Hi Peipei,

I had been thinking that the two identity errors local to the subscription process might be useful for kill-subscription output:
identity no-such-subscription
identity internal-error

As this type of information should be independent of NETCONF (i.e.,  perhaps applicable to RESTCONF or other transports), it would seem useful to keep.  This would also allow existing NETCONF RPC error conditions for access to the RPC to remain.

Eric

**Comment by ericvoit** [comment]
Subsumed into the larger (and extensive) Error-code discussions which were pursued within the Dezign team, as documented in the minutes.  Note: it is possible that this issue will return, as error-codes are again being discussed at we approach WGLC.
